#!/bin/bash

set -e -x

curl -k -o fly 'https://airbus.concourse.ci/api/v1/cli?arch=amd64&platform=linux'

chmod +x fly

./fly -t airbus login -c https://airbus.concourse.ci -n clara -u $AIRBUS_USERNAME -p $AIRBUS_PASSWORD -k

echo 3 | ./fly -t airbus hijack -j many-resource/so-many-resources -s failing-task -- echo hello | grep hello
